### ISSUE TITLE
Add support for additional labels

### ISSUE THREAD

**Issue by mikesir87** [mikesir87/helm-charts#3]
Add the ability for me to add my own labels to a specific service.

Given the following compose snippet...

```yaml
services:
  app:
    deploy:
      labels:
        foo:bar
```

the Deployment for the service `app` should have the label `foo=bar` added to it. No other services should have it added.
